# This is a basic workflow to help you get started with Actions

name: Deploy Next.js app

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install c3
        run : |
          npm i
          npm run build

      - name: Install packages
        working-directory: ./src/docs
        run: npm i

      - name: Build app
        working-directory: ./src/docs
        run: |
          npm run build
          touch ./out/.nojekyll
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          publish_dir: src/docs/out
          enable_jekyll: false
          github_token: ${{ secrets.GITHUB_TOKEN }}